name: Java CD with Gradle

on:
  push:
    branches: [ "develop" ]
    paths: 'backend/**'

defaults:
  run:
    working-directory: backend/banggood

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build with Gradle
      run: ./gradlew build

    - name: Push to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_SERVER_HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        source: "build/libs/*.jar"
        target: "source"
        rm: true

    - name: SSH to EC2 and run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_SERVER_HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd source
          ./deploy.sh
